# -*- coding: utf-8 -*-
"""RAG-using-langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HiMIDmyk-JiXmn3T0Dq-Drjz8a_Bv1LH
"""

!pip install -q -U \
    langchain \
    langchain_community \
    langchain_huggingface \
    langchain_text_splitters \
    huggingface_hub \
    sentence-transformers \
    transformers \
    faiss-cpu \
    pypdf

from google.colab import userdata
HF_TOKEN = userdata.get("HF_TOKEN")

if not HF_TOKEN:
  raise ValueError(
      "HF_TOKEN not found. Add HF_TOKEN to colab Secrets."
  )
print("Hugging face token loaded successfully.")

import os
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from huggingface_hub import InferenceClient

"""##Load the PDF"""

PDF_PATH = "/content/Hands-On Large Language Models.pdf"
loader = PyPDFLoader(PDF_PATH)
documents = loader.load()
print(f"Pages loaded: {len(documents)}")

"""##Split the document"""

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)
chunks = text_splitter.split_documents(documents)
print(f"Total chunks : {len(chunks)}")

"""##Load Qwen3 Embedding"""

import torch

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

from sentence_transformers import SentenceTransformer

embedding_model = HuggingFaceEmbeddings(
    model_name="Qwen/Qwen3-Embedding-0.6B",
    model_kwargs={
        "device": "cuda"
    },
   encode_kwargs={
       "normalize_embeddings": True
   }
)

"""##Create FAISS vector database"""

vectorstore = FAISS.from_documents(
    documents=chunks,
    embedding=embedding_model
)
print("FAISS database created successfully.")

"""##Create retriever"""

retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 5
    }
)

client = InferenceClient(
    token=HF_TOKEN,
    provider="auto"
)

"""##Test Qwen3-8B first"""

response = client.chat_completion(
    model="Qwen/Qwen3-8B",
    messages=[
        {
            "role" : "user",
            "content": "What is the difference between an LLM and traditional machine learning?"
        }
    ],
    temperature=0.7,
    max_tokens=2048,
    extra_body={
        "chat_template_kwargs": {
            "enable_thinking": False
        }
    }
)
print(response.choices[0].message.content)

"""##Build the RAG function"""

def ask_rag(question):

    # 1. Retrieve relevant documents

    retrieved_docs = retriever.invoke(question)

    # 2. Build context

    context_parts = []

    for doc in retrieved_docs:

        page = doc.metadata.get("page", "Unknown")

        context_parts.append(
            f"""
Source: {PDF_PATH}
Page: {page + 1}

Content:
{doc.page_content}
"""
        )

    context = "\n\n".join(context_parts)

    # 3. Create prompt

    prompt = f"""
You are a personal learning assistant.

Answer the user's question using ONLY the
information contained in the provided context.

Rules:

1. Do not use outside knowledge.
2. Do not invent information.
3. If the answer is not present in the context,
   say exactly:

   "I couldn't find the answer in the uploaded material."

4. Explain technical concepts clearly.
5. Prefer simple language.
6. When possible, mention the relevant source page.

CONTEXT
================================

{context}

================================

USER QUESTION
================================

{question}

================================

ANSWER
"""
    # 4. Ask Qwen3

    response = client.chat.completions.create(
        model="Qwen/Qwen3-8B",
        messages=[
            {
                "role": "system",
                "content": "You are a precise RAG-based learning assistant."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.1,
        max_tokens=800
    )

    answer = response.choices[0].message.content

    return answer, retrieved_docs

question = input("Ask your question: ")
answer, sources = ask_rag(question)
print("\n" + "="*70)
print("ANSWER")
print("="*70)

print(answer)

